services:
  api-service:
    build:
      context: ./apps/api-service
      dockerfile: Dockerfile
    container_name: sre-api-service
    ports:
      - "8000:8000"
    environment:
      APP_ENV: local
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: sre_platform
      DATABASE_USER: sre_admin
      DATABASE_PASSWORD: sre_password
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')",
        ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  postgres:
    image: postgres:17
    container_name: sre-postgres
    environment:
      POSTGRES_DB: sre_platform
      POSTGRES_USER: sre_admin
      POSTGRES_PASSWORD: sre_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sre_admin -d sre_platform"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: sre-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  prometheus:
    image: prom/prometheus:v3.5.0
    container_name: sre-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./platform/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - api-service

  grafana:
    image: grafana/grafana:12.1.0
    container_name: sre-grafana

    ports:
      - "3000:3000"

    depends_on:
      - prometheus

  node-exporter:
    image: prom/node-exporter:v1.9.1
    container_name: sre-node-exporter

    ports:
      - "9100:9100"

    restart: unless-stopped

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.52.1
    container_name: sre-cadvisor

    ports:
      - "8080:8080"

    privileged: true

    devices:
      - /dev/kmsg

    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro

    restart: unless-stopped

  postgres-exporter:
    image: quay.io/prometheuscommunity/postgres-exporter:v0.20.1
    container_name: sre-postgres-exporter
    environment:
      DATA_SOURCE_URI: "postgres:5432/sre_platform?sslmode=disable"
      DATA_SOURCE_USER: "sre_admin"
      DATA_SOURCE_PASS: "sre_password"
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "9187:9187"
    restart: unless-stopped

volumes:
  postgres_data:
